language: node_js
node_js:
- 12
# 将远程服务器加入信任列表
addons:
  ssh_known_hosts: 47.95.241.143
# 解密 id_rsa.enc，并修改 id_rsa 权限
before_install:
- openssl aes-256-cbc -K $encrypted_21400b344e4b_key -iv $encrypted_21400b344e4b_iv
  -in id_rsa.enc -out C:\\Users\\Administrator\\.ssh\\id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 连接远程服务器，并打印系统版本
after_success:
  - ssh root@47.95.241.143 'cat /etc/issue'
