language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: 47.95.241.143
before_install:
- openssl aes-256-cbc -K $encrypted_21400b344e4b_key -iv $encrypted_21400b344e4b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- ssh root@47.95.241.143 'cat /etc/issue'
